### ISSUE TITLE
Guest login (pinspiration credentials)

### ISSUE THREAD

**Issue by CPowell23** [CPowell23/pinspiration#10]
As a guest
When I visit the root path
I see a form to login
I also see a link to Register if I don't already have an account
I see error messages if I enter invalid credentials
If I enter valid credentials,
I see a successful login message
I am redirected to the dashboard page

**Comment by mollybrown** [comment]
Finished w/ Amy evening of 8/2. Still need to flesh out some additional tests, i.e. when user enters invalid credentials.
