### ISSUE TITLE
Create API for comments

### ISSUE THREAD

**Issue by CPowell23** [CPowell23/pinspiration#129]

**Comment by wlffann** [comment]
Users must be able to “comment” in some capacity.
* This may be in the form of a “review” depending on your app’s domain.
* You must consume internal API endpoints that support CRUD functionality of comments/reviews.

Your API for comments/reviews must be authenticated for external use.
* External users must be provided an API key that they use to make requests to your API.
* Extensive documentation of your API. Some students have used swagger.io for this, but it’s not required.
