### ISSUE TITLE
Logged in user can delete their account

### ISSUE THREAD

**Issue by CPowell23** [CPowell23/pinspiration#17]

**Comment by wlffann** [comment]
As a User
When I am logged in
I can click on the Account icon
And I see my Profile page
From there, I can click on the Settings icon
And I am redirected to the Account Info page
I can click on "Deactivate Account'
I can click on "Permanently close my account"
I am prompted to confirm my account closing
I can click on "Send email confirmation"
And I am redirected to the Log In page
