### ISSUE TITLE
Logged in user can create pins and add them to their boards

### ISSUE THREAD

**Issue by CPowell23** [CPowell23/pinspiration#19]

**Comment by wlffann** [comment]
As a User
When I am logged in
I can click on the Account icon
And I see my Profile page
I can click on "Pins"
I can choose to upload a photo 
I am prompted to upload an image from my computer
I use the file browser to select an image
I click on "Upload" and I see the image 
I choose which board to add the Pin to
I see a message that the Board was updated
And I am redirected to my pins page
