### ISSUE TITLE
Logged in user can see details of one user that they are following

### ISSUE THREAD

**Issue by CPowell23** [CPowell23/pinspiration#22]

**Comment by wlffann** [comment]
As a User
When I am logged in
I can click on the Account icon
And I see my Account page
I can see the number of Users I am following
I can click on "Following"
And I can see all of the Users that I am following
I can click on one User's picture
And I am redirected to that User's page
I can see the User's name, description, number of people following and being followed by
And I can choose to see the User's boards or Pins
